### ISSUE TITLE
Library evaluation tracking issue

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/bitflags#80]
- [x] [Move docs to the crate level](https://github.com/rust-lang-nursery/bitflags/issues/75)
- [x] [Add CI badges to Cargo.toml](https://github.com/rust-lang-nursery/bitflags/issues/76)
- [x] [Add keywords and categories to Cargo.toml](https://github.com/rust-lang-nursery/bitflags/issues/77)
- [x] [Add html_root_url attribute](https://github.com/rust-lang-nursery/bitflags/issues/78)
- [x] [Remove mention of stable 'assignment_ops' feature from docs](https://github.com/rust-lang-nursery/bitflags/issues/79)
- [x] [Add an example of implementing Default](https://github.com/rust-lang-nursery/bitflags/issues/66)
- [x] [Add an example illustrating what the macro-generated API's look like](https://github.com/rust-lang-nursery/bitflags/issues/81)
- [x] [Get rid of internal case from macro](https://github.com/rust-lang-nursery/bitflags/issues/63)
- [x] [Make crate clippy-clean](https://github.com/rust-lang-nursery/bitflags/issues/41)
- [x] [Automatically implement Hex, Octal, Binary](https://github.com/rust-lang-nursery/bitflags/issues/82)
- [x] [Fix Debug representation of empty bitflags](https://github.com/rust-lang-nursery/bitflags/issues/64)
- [x] [Use of semis instead of commas in bitflags dsl](https://github.com/rust-lang-nursery/bitflags/issues/65)
- [x] [Change "flags" to "struct" in dsl](https://github.com/rust-lang-nursery/bitflags/issues/67)
- [ ] Bump version to 1.0 (after all else).

This is the tracking issue for the [evaluation](https://public.etherpad-mozilla.org/p/rust-crate-eval-bitflags) performed by the libs team last week.

**Comment by brson** [comment]
cc @rust-lang-nursery/libs

**Comment by Cldfire** [comment]
`Change "flags" to "struct" in dsl` should be marked as completed: https://github.com/rust-lang-nursery/bitflags/pull/84

**Comment by Amanieu** [comment]
Should we hold off on 1.0 until the crate is converted to use associated constants (#24)? The discussion in rust-lang/rust#29646 seems to be tending towards stabilizing them soon.

**Comment by sfackler** [comment]
I would love associated constants for bitflags, so I'd vote for yes if it looks like that'll be landing.

**Comment by brson** [comment]
That would make bitflags incompatible with quite recent rust's right? That seems kinda undesirable.

**Comment by sfackler** [comment]
It'd obviously require a major version bump on bitflags, but the ergonomic benefits of not having a bunch of random constants of different types thrown into the root module is pretty huge.

**Comment by robo9k** [comment]
`Add CI badges to Cargo.toml` should be marked as completed due to #100

**Comment by opilar** [comment]
All issues are completed. The library is ready to be evaluated.

**Comment by crumblingstatue** [comment]
Is it in any way problematic to release a bitflags 2.0 soon after it incorporates associated consts?

If so, I would prefer to wait for associated consts support before 1.0.

**Comment by crumblingstatue** [comment]
We might also want to consider #72 , since `pub(restricted)` will land in next stable.

Then again, this could also be supported in bitflags 2.0.

**Comment by theduke** [comment]
Since associated constants are in FCP for stabilization, I'd rather wait a bit longer for a `1.0` rather than upgrading to `2.0` a few months later.

**Comment by brson** [comment]
Wow thanks @opilar  @crumblingstatue @theduke !

**Comment by alexcrichton** [comment]
1.0 published!

**Comment by robinst** [comment]
Yay! @alexcrichton could you add release notes for 1.0.0 here?: https://github.com/rust-lang-nursery/bitflags/releases

(see https://github.com/rust-lang-nursery/bitflags/issues/121)
